version: '1.0'
services: 
  app: 
    container_name: roadrunners-front
    build: .
    ports:
      - 4200:80
    expose:
      - 80
    environment:
      URL: '${URL}'
      DOMAIN: '${DOMAIN}'
      CLIENT_ID: '${CLIENT_ID}'
      AUDIENCE: '${AUDIENCE}'