export const brands = [
  {
    name: 'Acura',
    logo: './assets/brands-logo/acura-logo.png',
    models: [
      'MDX',
      'RDX',
      'RSX',
      'T L',
      'TLX',
      'TSX',
    ],
  },
  {
    name: 'Alfa Romeo',
    logo: './assets/brands-logo/alfa.png',
    models: [
      '159',
      'Giulia',
      'Stelvio',
    ],
  },
  {
    name: 'Audi',
    logo: './assets/brands-logo/audi-logo.png',
    models: [
      'A1',
      'A3',
      'A4',
      'A5',
      'A6',
      'A7',
      'A8',
      'E-Tron',
      'Q2',
      'Q3',
      'Q5',
      'Q7',
      'Q8',
      'R8',
      'RS',
      'RS E-TRON GT',
      'RS3',
      'S3',
      'S4',
      'S6',
      'S7',
      'S8',
      'SQ5',
      'SQ7',
      'TT',
    ],
  },
  {
    name: 'Bmw',
    logo: './assets/brands-logo/bmw.png',
    models: [
      'B7',
      'i3',
      'M',
      'Serie 3',
      'Serie 4',
      'Serie 5',
      'Serie 6',
      'Serie 7',
      'X',
      'Z',
    ],
  },
  {
    name: 'Buick',
    logo: './assets/brands-logo/buick.png',
    models: [
      'Enclave',
      'Encore',
    ],
  },
  {
    name: 'Cadillac',
    logo: './assets/brands-logo/cadillac.png',
    models: [
      'ATS',
      'Brougham',
      'CTS',
      'De Ville',
      'Escalade',
      'Fletwood',
      'Seville',
      'SRX',
      'XT4',
      'XTS',
    ],
  },
  {
    name: 'Changan',
    logo: './assets/brands-logo/changan.png',
    models: [
      'Cargo Box Refrigerada',
      'Chana',
      'CS 15',
      'CS 35',
      'CS 55',
      'CS 75',
      'CS 85',
      'F 70',
      'Hunter',
      'Star 5',
      'Star5 Furgon',
      'Uni-K',
      'Uni-K elite',
      'UNI-T',
      'X 7',
    ],
  },
  {
    name: 'Chevrolet',
    logo: './assets/brands-logo/chevrolet.png',
    models: [
      'Avalanche',
      'Aveo',
      'Blazer',
      'Bolt',
      'Camaro',
      'Caprice Classic',
      'Captiva',
      'City Express',
      'CMV',
      'Colorado',
      'Corvette',
      'Cruze',
      'DAMAS',
      'Equinox',
      'Express',
      'Groove',
      'Impala',
      'Labo',
      'Lumina',
      'Malibu',
      'N 300',
      'N 400',
      'Nova',
      'Orlando',
      'Silverado',
      'Sonic',
      'Spark',
      'Suburban',
      'Tahoe',
      'Tracker',
      'Trail blazer',
      'Trailblazer',
      'Traverse',
      'Trax',
      'Volt',
      'Z 71',
    ],
  },
  {
    name: 'Daihatsu',
    logo: './assets/brands-logo/daihatsu.png',
    models: [
      'Boon',
      'Hijet',
      'Mira',
      'Tanto',
      'Terios',
    ],
  },
  {
    name: 'Dodge',
    logo: './assets/brands-logo/dodge.png',
    models: [
      'Avenger',
      'Caliber',
      'Caravan',
      'Challenger',
      'Charger',
      'Dart',
      'Durango',
      'Grand Caravan',
      'Journey',
      'Nitro',
      'Ram',
    ],
  },
  {
    name: 'Dongfeng',
    logo: './assets/brands-logo/dongfeng.png',
    models: [
      'AX7',
      'Cargo Box',
      'DFSK',
      'EB HS M5 ELECTRIC',
      'EM10',
      'EV 400',
      'Forthing',
      'Glory',
      'Mini Truck',
      'Rich 6',
      'Star Bus',
    ],
  },
  {
    name: 'Ferrari',
    logo: './assets/brands-logo/ferrari.png',
    models: [
      '296 GTB',
      '458',
      '488',
      'California',
      'F-430',
      'F8',
      'Roma',
      'SF90 Spider',
      'SF90 Stradale',
    ],
  },
  {
    name: 'Fiat',
    logo: './assets/brands-logo/fiat.png',
    models: [
      '500',
      'ARGO',
      'AUDACE TURBO 200',
      'Ducato',
      'Fastback',
      'Fiorino',
      'Fullback',
      'Pulse',
      'Punto',
    ],
  },
  {
    name: 'Ford',
    logo: './assets/brands-logo/ford-logo.png',
    models: [
      'Bronco',
      'C Max',
      'E-350',
      'E-450',
      'Eco Sport',
      'Econoline',
      'EDGE',
      'Escape',
      'Everest',
      'Excursion',
      'Expedition',
      'Explorer',
      'F 150',
      'F 250',
      'F 350',
      'F-450',
      'Fiesta',
      'Figo',
      'Focus',
      'Fusion',
      'M151 MUTT',
      'Mustang',
      'Mustang Mach-E',
      'Ranger',
      'Taurus',
      'Territory',
      'Transit',
    ],
  },
  {
    name: 'Great wall',
    logo: './assets/brands-logo/great-wall.png',
    models: [
      'Kingkong Poer',
      'Poer',
      'Tank 300',
    ],
  },
  {
    name: 'Honda',
    logo: './assets/brands-logo/honda-logo.png',
    models: [
      'Accord',
      'Acty',
      'BR-V',
      'Civic',
      'Clarity',
      'CR-V',
      'CR-Z',
      'ENP1',
      'ENS1',
      'Fit',
      'HR-V',
      'Insight',
      'MNV',
      'N-WGN',
      'Odyssey',
      'Passport',
      'Pilot',
      'Prelude',
      'Ridgeline',
      'S 2000',
    ],
  },
  {
    name: 'Hyundai',
    logo: './assets/brands-logo/hyundai-logo.png',
    models: [
      'Accent',
      'Avante',
      'Azera',
      'Cantus',
      'Elantra',
      'Genesis',
      'Grand I 10',
      'Grand Santa Fe',
      'Grand Starex',
      'Grandeur',
      'H 1',
      'i 10',
      'i 20',
      'Ioniq',
      'KONA',
      'Palisade',
      'Santa Fe',
      'Sonata',
      'Starex',
      'Staria',
      'Tucson',
      'Veloster',
      'Venue',
      'Veracruz',
      'Verna',
      'XG 350',
    ],
  },
  {
    name: 'Infiniti',
    logo: './assets/brands-logo/infiniti.png',
    models: [
      'F35',
      'FQ-56',
      'FX-35',
      'JX-35',
      'Q-50',
      'QX-30',
      'QX-50',
      'QX-55',
      'QX-56',
      'QX-60',
      'QX-70',
      'QX-80',
    ],
  },
  {
    name: 'Isuzu',
    logo: './assets/brands-logo/isuzu.png',
    models: [
      'DMAX',
      'Mux',
      'Rodeo',
    ],
  },
  {
    name: 'JAC Motors',
    logo: './assets/brands-logo/jac.png',
    models: [
      'FRISON',
      'FRISON T8 PRO',
      'JS3',
      'Js4',
      'JS4 FLAGSHIP',
      'JS8',
      'JS8 FLAGSHIP',
      'S2',
      'S3',
      'T6',
      'T8',
    ],
  },
  {
    name: 'Jaguar',
    logo: './assets/brands-logo/jaguar.png',
    models: [
      'F-Pace',
      'XE',
      'XF',
      'XJ6',
      'XJ8',
    ],
  },
  {
    name: 'Jeep',
    logo: './assets/brands-logo/jeep.png',
    models: [
      'Cherokee',
      'Comander',
      'Commander',
      'Compass',
      'Gladiator',
      'Grand Cherokee',
      'Grand Cherokee L',
      'Liberty',
      'Patriot',
      'Renegade',
      'Wagoneer',
      'Willys',
      'Wrangler',
    ],
  },
  {
    name: 'Kia',
    logo: './assets/brands-logo/kia.png',
    models: [
      'Carens',
      'Carnival',
      'Cerato',
      'Force',
      'Forte',
      'K-5',
      'K-7',
      'K900',
      'Lotze',
      'Morning',
      'Niro',
      'Optima',
      'Picanto',
      'Ray',
      'Rio',
      'Rondo',
      'Sedona',
      'Seltos',
      'Soluto',
      'Sonet',
      'Sorento',
      'Soul',
      'Sportage',
      'Telluride',
    ],
  },
  {
    name: 'King long',
    logo: './assets/brands-logo/king-long.png',
    models: [
      '16 Pasajeros',
    ],
  },
  {
    name: 'Lamborghini',
    logo: './assets/brands-logo/lamborghini.png',
    models: [
      'Gallardo',
      'Huracan',
      'Urus',
    ],
  },
  {
    name: 'Land rover',
    logo: './assets/brands-logo/land-rover.png',
    models: [
      'Defender',
      'Discovery',
      'Freelander',
      'Range Rover',
    ],
  },
  {
    name: 'Lexus',
    logo: './assets/brands-logo/lexus.png',
    models: [
      'ES',
      'GS',
      'GS F',
      'GX',
      'IS',
      'LC',
      'LS',
      'LX',
      'NX',
      'RC',
      'RC F',
      'RX',
      'RZ',
      'UX',
    ],
  },
  {
    name: 'Lincoln',
    logo: './assets/brands-logo/lincoln.png',
    models: [
      'Aviator',
      'Continental',
      'Corsair',
      'MKC',
      'MKX',
      'Navigator',
    ],
  },
  {
    name: 'Maserati',
    logo: './assets/brands-logo/maserati.png',
    models: [
      'Ghibli',
      'Gran Turismo',
      'Grecale',
      'Levante',
      'MC20',
      'Quattroporte',
    ],
  },
  {
    name: 'Maxus',
    logo: './assets/brands-logo/maxus.png',
    models: [
      'D60',
      'Euniq 5',
      'Euniq 6',
      'EV30',
      'T60',
      'T90',
    ],
  },
  {
    name: 'Mazda',
    logo: './assets/brands-logo/mazda.png',
    models: [
      '2',
      '3',
      '323',
      '6',
      'Axela',
      'B 2000',
      'Bongo',
      'BT-50',
      'CX-3',
      'CX-30',
      'CX-5',
      'CX-60',
      'CX-7',
      'CX-9',
      'CX-90',
      'Demio',
      'Miata',
      'RX-7',
      'Scrum',
    ],
  },
  {
    name: 'Mclaren',
    logo: './assets/brands-logo/mclaren.png',
    models: [
      '570',
      '650',
      '720',
    ],
  },
  {
    name: 'Mercedes-Benz',
    logo: './assets/brands-logo/mercedes-logo.png',
    models: [
      'Clase A',
      'Clase C',
      'Clase CL',
      'Clase CLA',
      'Clase CLS',
      'Clase E',
      'Clase EQA',
      'Clase G',
      'Clase GL',
      'Clase GLA',
      'Clase GLB',
      'Clase GLC',
      'Clase GLE',
      'Clase GLK',
      'Clase GLS',
      'Clase GT',
      'Clase ML',
      'Clase S',
      'Clase SL',
      'Clase V',
      'Clase X',
      'EQS',
      'Gazell',
      'Metris',
      'SEC',
      'SEL',
      'Smart',
      'Sprinter',
    ],
  },
  {
    name: 'Mini',
    logo: './assets/brands-logo/mini.png',
    models: [
      'Cooper',
    ],
  },
  {
    name: 'Mitsubishi',
    logo: './assets/brands-logo/mitsubishi.png',
    models: [
      '3000 GT',
      'ASX',
      'Eclipse',
      'Endeavor',
      'Evolution',
      'i',
      'L 200',
      'Lancer',
      'Minicab Truck',
      'Mirage',
      'Montero',
      'Montero Pajero',
      'Montero Sport',
      'Nativa',
      'Outlander',
      'Pajero',
      'Raider',
      'Xpander',
      'Zinger',
    ],
  },
  {
    name: 'Nissan',
    logo: './assets/brands-logo/nissan.png',
    models: [
      '1200',
      '300 ZX',
      '370-Z',
      'Ad Van',
      'Ad Wagon',
      'Almera',
      'Altima',
      'Armada',
      'Caravan',
      'clipper',
      'D 22',
      'Frontier',
      'GT-R',
      'Juke',
      'Kicks',
      'Latio',
      'Leaf',
      'March',
      'Maxima',
      'Murano',
      'Navara',
      'Note',
      'NT',
      'NV',
      'Pathfinder',
      'Patrol',
      'Pick Up',
      'Qashqai',
      'Quest',
      'Rogue',
      'Sentra',
      'Serena',
      'TIIDA',
      'TITAN',
      'Urvan',
      'Vanette',
      'Versa',
      'Wingroad',
      'X-Trail',
      'Xterra',
    ],
  },
  {
    name: 'Peugeot',
    logo: './assets/brands-logo/peugeot.png',
    models: [
      '2008',
      '206',
      '208',
      '3008',
      '308',
      '5008',
      'E-2008',
      'Landtrek',
      'Partner',
      'RCZ',
      'Rifter',
    ],
  },
  {
    name: 'Pontiac',
    logo: './assets/brands-logo/pontiac.png',
    models: [
      'Fiero',
      'Firebird',
    ],
  },
  {
    name: 'Porsche',
    logo: './assets/brands-logo/porsche.png',
    models: [
      '911',
      '944',
      'Boxster',
      'Carrera',
      'Cayenne',
      'Cayman',
      'GT3',
      'Macan',
      'Panamera',
      'Targa',
      'Taycan',
    ],
  },
  {
    name: 'Ram',
    logo: './assets/brands-logo/ram.png',
    models: [
      '1000',
      '1200',
      '1500',
      '700',
      'Promaster',
      'REBEL',
    ],
  },
  {
    name: 'Renault',
    logo: './assets/brands-logo/renault.png',
    models: [
      '1000',
      '1200',
      '1500',
      '700',
      'Promaster',
      'REBEL',
    ],
  },
  {
    name: 'Rivian',
    logo: './assets/brands-logo/rivian.png',
    models: [
      'R1T',
    ],
  },
  {
    name: 'Rolls Royce',
    logo: './assets/brands-logo/rollsroyce.png',
    models: [
      'Phantom',
    ],
  },
  {
    name: 'Suzuki',
    logo: './assets/brands-logo/suzuki.png',
    models: [
      'EECO',
      'Alto',
      'APV',
      'Carry',
      'Celerio',
      'Ciaz',
      'Dzire',
      'Fronx',
      'Grand Vitara',
      'Jimny',
      'S-Cross',
      'Swift',
      'SX 4',
      'Vitara',
      'XL7',
    ],
  },
  {
    name: 'Tesla',
    logo: './assets/brands-logo/tesla-logo.png',
    models: [
      'Model S',
      'Model 3',
      'Model X',
      'Model Y',
    ],
  },
  {
    name: 'Toyota',
    logo: './assets/brands-logo/toyota-logo.png',
    models: [
      '4 Runner',
      'Agya',
      'Alphard',
      'Aqua',
      'BZ4X',
      'C-HR',
      'Camry',
      'Coms',
      'Corolla',
      'Corolla Cross',
      'Cressida',
      'Crown',
      'FJ Cruiser',
      'Fortuner',
      'Grand Highlander',
      'Hiace',
      'Highlander',
      'Hilux',
      'Land Cruiser',
      'Land Cruiser Prado',
      'Lite-Ace',
      'Matrix',
      'MR2',
      'Passo',
      'Pick Up',
      'Pixis',
      'Prius',
      'Probox',
      'Raize',
      'RAV4',
      'Rush',
      'Scion',
      'Sequoia',
      'Sienna',
      'Supra',
      'Tacoma',
      'Town-Ace',
      'Tundra',
      'Venza',
      'VITZ',
      'Yaris',
    ],
  },
  {
    name: 'Volkswagen',
    logo: './assets/brands-logo/volkswagen.png',
    models: [
      'Amarok',
      'Atlas',
      'Beetle',
      'Crossfox',
      'Gol',
      'Golf',
      'ID-3',
      'ID-4',
      'ID-6',
      'Jetta',
      'Nivus',
      'Passat',
      'Saveiro',
      'T-Cross',
      'Taos',
      'Teramont',
      'Tiguan',
      'Touareg',
    ],
  },
  {
    name: 'Volvo',
    logo: './assets/brands-logo/volvo.png',
    models: [
      'C30',
      'C40',
      'S60',
      'S90',
      'XC40',
      'XC60',
      'XC90',
    ],
  },
];